name: Insomnia API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install -g insomnia-inso
          sudo apt-get install -y google-cloud-sdk

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCLOUD_AUTH }}" | base64 --decode > gcloud-auth.json
          gcloud auth activate-service-account --key-file=gcloud-auth.json
          gcloud auth configure-docker

      - name: Run Insomnia API Tests
        run: |
          chmod +x run-inso.sh
          ./run-inso.sh

      - name: Upload Test Logs
        uses: actions/upload-artifact@v4.6.0
        with:
          name: inso-test-logs
          path: results/
